version: '3.8'

services:
  db:
    image: postgres:14
    container_name: cosmo_conquest_db
    environment:
      POSTGRES_DB: cosmo_conquest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  

volumes:
  db_data:
